spring.application.name=csgoskinsbackend

spring.datasource.url=jdbc:postgresql://localhost:5432/csgoskins2
spring.datasource.username=alwaysintilte_admin
spring.datasource.password=alwaysintilte_password

spring.redis.host=localhost
spring.redis.port=6379